import { Tile } from './tile'

export const MockTiles: Tile[] = [
    {
        id: 1,
        title: 'Home',
        subtitle: 'where the food is',
        avatar: 'home',
        content: 'This is some short content.',
        href: '',
        featured: false,
    },
    {
        id: 2,
        title: 'Baby',
        subtitle: 'Subtitle',
        avatar: '',
        content: 'This is some short content.',
        href: 'http://mnr2015.com/baby',
        featured: true,
    },
    {
        id: 3,
        title: 'Galleries',
        subtitle: 'Subtitle',
        avatar: '',
        content: 'This is some short content.',
        href: 'http://mnr2015.com/galleries',
        featured: true,
    },
    {
        id: 4,
        title: 'Blog',
        subtitle: 'where the goods are',
        avatar: '',
        content: 'This is some short content.',
        href: 'http://blog.mnr2015.com',
        featured: false,
    },
    {
        id: 5,
        title: 'Dev/Staging',
        subtitle: 'Subtitle',
        avatar: '',
        content: 'This is some short content.',
        href: 'http://dev.mnr2015.com',
        featured: false,
    },
    {
        id: 6,
        title: 'Expo',
        subtitle: 'Subtitle',
        avatar: '',
        content: 'This is some short content.',
        href: 'http://dev2.mnr2015.com',
        featured: false,
    },
]
